### ISSUE TITLE
Dask threads vs workers vs OMP thread vs resources

### ISSUE THREAD

**Issue by afni-dglen** [leej3/afni#3]
Use optimal number of Dask workers and threads for OpenMP threads used by AFNI commands.On LocalCluster, the multiplicative product, threads x workers, seem to set the number of delayed processes. 
So 5 workers or 5 threads are similar. Cores per delay seem to be 4 on laptop. Setting 1 thread/worker uses less memory on 3dQwarp ~800MB vs 1GB on 5, but they wait for the other workers to end before starting the next batch of workers. Using multiple threads and a single worker uses more memory but seems to let processes continue as the processes finish. There are options for setting number of workers and threads, but this should be more automatic and understandable.

**Comment by leej3** [comment]
https://github.com/leej3/dask_resource_constraint_example
